project:
  type: website

website:
  title: "Aaron Peterseil's Website"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: My Projects
        
  page-footer:
    right: "&copy; 2024, Aaron Peterseil"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


execute:
  freeze: auto

